Import 3.14-0.5 release

diff --git a/rootfs/skel/bin/pml b/rootfs/skel/bin/pml
--- a/rootfs/skel/bin/pml
+++ b/rootfs/skel/bin/pml
@@ -2,7 +2,16 @@
 
 set -e
 
-waketimer=/sys/devices/*.waketimer
+function find_waketimer {
+	for i in /sys/bus/platform/drivers/brcm-waketimer/*
+	do
+		[ -d $i ] && echo $i && return 0
+	done
+	echo "Error: no wake-timer found" >&2
+	exit 1
+}
+
+waketimer=`find_waketimer`
 power_sysfs=/sys/power/state
 cpu_sysfs=/sys/devices/system/cpu
 
@@ -19,11 +28,12 @@ wakeup_time=1
 function usage
 {
 	echo "pml: power management script version 1.0"
-	echo "Usage: pml [-lN] [-mMODE] [-tchd] [-sN] [-wN]"
+	echo "Usage: pml [-lN] [-mMODE] [-tchdp] [-sN] [-wN]"
 	echo "where:"
 	echo "    -lN    - number of loops (decimal:1); negative value - infinite loop"
 	echo "    -mMODE - system suspend debug mode (none, core, platform, devices, freezer:none)"
 	echo "    -d     - deep standby (s3)"
+	echo "    -p     - cold standby (S5); shut down gracefully"
 	echo "    -t     - turn secondary CPUs off before test (no)"
 	echo "    -c     - hotplug-cycle secondary CPUs after each iteration (no)"
 	echo "    -sN    - seconds to sleep between iterations (decimal:0)"
@@ -40,7 +50,15 @@ function failure
 }
 
 function supported_pmmodes {
-	cat $power_sysfs
+	local modes=`cat $power_sysfs`
+	echo -n $modes
+
+	# Hack in a 'poweroff' mode
+	if which poweroff > /dev/null 2>&1
+	then
+		[ "$modes" != "" ] && echo -n " "
+		echo -n "poweroff"
+	fi
 }
 
 function supports_pmmode {
@@ -74,11 +92,13 @@ function set_cpus_power {
 }
 
 quit_on_failure=false
-while getopts "hl:m:tcs:w:x:X:d" option
+while getopts "hl:m:tcs:w:x:X:dp" option
 do
 	case $option in
 	d)
 		pm_mode=mem ;;
+	p)
+		pm_mode=poweroff ;;
 	x)
 		command=$OPTARG ;;
 	X)
@@ -120,6 +140,13 @@ fi
 set_cpus_power $tp_all
 
 set_sleep_timeout $wakeup_time
+
+# S5 ==> poweroff
+if [ "$pm_mode" = "poweroff" ]; then
+	echo "Entering S5 soft off state, wakeup_time=$wakeup_time"
+	poweroff
+	exit $?
+fi
 
 function one_pass
 {
diff --git a/rootfs/skel/bin/stbutil b/rootfs/skel/bin/stbutil
--- a/rootfs/skel/bin/stbutil
+++ b/rootfs/skel/bin/stbutil
@@ -106,6 +106,8 @@ function get_mtd_attr()
 
 function flash_is_nand()
 {
+	mtdX=$1
+	! get_mtd_attr $mtdX type flash_type && echo "Cannot get flash type" && exit 1
 	if [ "$flash_type" = "nand" ] || [ "$flash_type" = "mlc-nand" ]; then
 		return 0 # note the backwards shell return-code semantics
 	else
@@ -183,9 +185,12 @@ function handle_opt_1()
 {
 	mtd=/dev/mtd${kernel_part}
 
+	echo "Writing kernel to $mtd"
+	echo
+
 	tftp_fetch $tftphost $tftppath/vmlinuz-$plat /tmp/vmlinuz
 	flash_erase $mtd 0 0
-	if flash_is_nand; then
+	if flash_is_nand $kernel_part; then
 		nandwrite -p $mtd /tmp/vmlinuz
 	else
 		dd if=/tmp/vmlinuz of=$mtd
@@ -218,7 +223,6 @@ function handle_opt_2()
 	rem_img=ubifs-$(($flash_erasesize / 1024))k-$(($flash_writesize))-${plat}.img
 
 	if tftp_fetch -q $tftphost $tftppath/$rem_img /tmp/rootfs.img; then
-		flash_erase $mtd 0 0
 		ubiformat $mtd --yes --flash-image=/tmp/rootfs.img
 	else
 		echo ""
@@ -226,7 +230,6 @@ function handle_opt_2()
 		echo ""
 		rem_img=nfsroot-${plat}.tar.bz2
 		tftp_fetch $tftphost $tftppath/$rem_img /tmp/rootfs.tar.bz2
-		flash_erase $mtd 0 0
 		ubiformat $mtd --yes
 		ubiattach -m $rootfs_part -d 0
 		# NOTE: ubiattach/mdev may run asynchronously
@@ -294,8 +297,7 @@ function handle_opt_4()
 	rem_img=squashfs-${plat}.img
 
 	tftp_fetch $tftphost $tftppath/$rem_img /tmp/rootfs.img
-	flash_erase $mtd 0 0
-	if flash_is_nand; then
+	if flash_is_nand $rootfs_part; then
 		imgsize=$(du -k /tmp/rootfs.img | sed 's/[ \t].*//')
 		ubiformat $mtd --yes
 		ubiattach -m $rootfs_part -d 0
@@ -315,6 +317,7 @@ function handle_opt_4()
 		ubidetach -d 0
 		cmdline="ubi.mtd=${rootfs_mtd_name} root=/dev/mtdblock${newpart}"
 	else
+		flash_erase $mtd 0 0
 		newpart=$rootfs_part
 		dd if=/tmp/rootfs.img of=$mtd
 		cmdline="root=/dev/mtdblock${rootfs_part}"
@@ -328,7 +331,7 @@ function handle_opt_4()
 	echo ""
 	echo "To mount the filesystem now:"
 	echo ""
-	if flash_is_nand; then
+	if flash_is_nand $rootfs_part; then
 		echo "  ubiattach -m $rootfs_part"
 		echo "  mount /dev/mtdblock${newpart} /mnt/flash"
 		echo ""
@@ -577,7 +580,7 @@ if [ -z $rootfs_part ]; then
 	suf4="$suf2"
 fi
 
-if flash_is_nand; then
+if flash_is_nand $rootfs_part; then
 	suf3="(not available)"
 	suf4="(uses UBI)"
 fi
